name: 'Orca Security Scan'
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  orca-fs-scan:
    name: 'Orca Scan'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v3

      - name: 'Run Orca Scan'
        uses: orcasecurity/shiftleft-fs-action@v1
        with:
          api_token: ${{ secrets.ORCA_SECURITY_API_TOKEN }}
          project_key: ${{ env.PROJECT_KEY }}
          path:
            "."